/**
 * Application-wide error codes. Returned in the `error` field of the standard
 * error response so the Flutter client can branch on stable codes rather than
 * parsing the human-readable message.
 */
export const ErrorCodes = {
  // Validation / request shape
  VALIDATION_ERROR: 'VALIDATION_ERROR',
  INVALID_OBJECT_ID: 'INVALID_OBJECT_ID',
  INVALID_FILE: 'INVALID_FILE',

  // Auth
  UNAUTHORIZED: 'UNAUTHORIZED',
  FORBIDDEN: 'FORBIDDEN',
  TOKEN_EXPIRED: 'TOKEN_EXPIRED',
  INVALID_CREDENTIALS: 'INVALID_CREDENTIALS',

  // Resources
  NOT_FOUND: 'NOT_FOUND',
  USER_NOT_FOUND: 'USER_NOT_FOUND',
  PRODUCT_NOT_FOUND: 'PRODUCT_NOT_FOUND',
  ORDER_NOT_FOUND: 'ORDER_NOT_FOUND',
  TABLE_NOT_FOUND: 'TABLE_NOT_FOUND',
  CATEGORY_NOT_FOUND: 'CATEGORY_NOT_FOUND',
  DINING_SESSION_NOT_FOUND: 'DINING_SESSION_NOT_FOUND',
  WAITER_REQUEST_NOT_FOUND: 'WAITER_REQUEST_NOT_FOUND',
  NOTIFICATION_NOT_FOUND: 'NOTIFICATION_NOT_FOUND',
  BILL_NOT_FOUND: 'BILL_NOT_FOUND',

  // Conflict / state
  DUPLICATE_EMAIL: 'DUPLICATE_EMAIL',
  INVALID_STATUS_TRANSITION: 'INVALID_STATUS_TRANSITION',
  ORDER_NOT_CANCELLABLE: 'ORDER_NOT_CANCELLABLE',
  TABLE_NOT_AVAILABLE: 'TABLE_NOT_AVAILABLE',
  SESSION_CLOSED: 'SESSION_CLOSED',
  PRODUCT_UNAVAILABLE: 'PRODUCT_UNAVAILABLE',

  // Server
  INTERNAL_ERROR: 'INTERNAL_ERROR',
} as const;

export type ErrorCode = keyof typeof ErrorCodes | (typeof ErrorCodes)[keyof typeof ErrorCodes];
